# Generated by Django 3.2 on 2021-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=23)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Message', models.CharField(max_length=255)),
            ],
        ),
    ]
